version: '3.8'

services:
  accounts:
    image: vamckrishna/accounts
    ports:
      - "8080:8080"
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    networks:
      - banks-app-network

  loans:
    image: vamckrishna/loans
    ports:
      - "8090:8090"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      - configserver
    networks:
      - banks-app-network

  cards:
    image: vamckrishna/cards
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8071/
    depends_on:
      - configserver
    networks:
      - banks-app-network

  configserver:
    image: vamckrishna/configserver
    ports:
      - "8071:8071"
    networks:
      - banks-app-network

networks:
  banks-app-network:
  