spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false # This tells the gateway to use the service registry to find the microservices
          lower-case-service-id: true # This tells the gateway to use lowercase service IDs
  data:
    redis:
      connection-timeout: 1000
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  traces:
    tags:
      application: ${spring.application.name}
  logs:
    tags:
      application: ${spring.application.name}
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: gatewayserver
    description: Gateway Server or API gateway or Edge Server Microservice
    version: 1.0.0

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

