spring:
  application:
    name: eurekaserver
  config:
    #file: ${user.home}/config/eurekaserver.yml # This is the location of the config files when using the native profile
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      enabled: true
  traces:
    tags:
      application: ${spring.application.name}
  logs:
    tags:
      application: ${spring.application.name}
  metrics:
    tags:
      application: ${spring.application.name}