apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: webstore
spec:
  replicas: 1
  selector:
      matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:latest
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: gateway-config
          - secretRef:
              - name: gateway-secret
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_REPORTER_LOG_SPANS
          value: "true"
        - name: JAEGER_REPORTER_FLUSH_INTERVAL
          value: "1s"
        - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
          value: "100"
        - name: JAEGER_REPORTER_MAX_BUFFER_SIZE
          value: "100"
        - name: JAEGER_REPORTER_MAX_UDP_PACKET_SIZE
          value: "65000"
        - name: JAEGER_ENDPOINT
          value: http://jaeger:14268/api/traces
        - name: JAEGER_USER
          value: admin
        - name: JAEGER_PASSWORD
          value: admin
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_REPORTER_LOG_SPANS
          value: "true"
        - name: JAEGER_REPORTER_FLUSH_INTERVAL
          value: "1s"
        - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
          value: "100"
        - name: JAEGER_REPORTER_MAX_BUFFER_SIZE
          value: "100"
        - name: JAEGER_REPORTER_MAX_UDP_PACKET_SIZE
          value: "65000"
        - name: JAEGER_ENDPOINT
          value: http://jaeger:14268/api/traces
        - name: JAEGER_USER
          value: admin
        - name: JAEGER_PASSWORD
          value: admin
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_AGENT_PORT
